### ISSUE TITLE
Don't swallow errors

### ISSUE THREAD

**Issue by benjamingr** [acdlite/redux-promise#25]
The fact this middleware swallows errors makes debugging hard. I think for the very least in addition to marking `error: true` it would be useful to call a hook notifying the user of the error - at least when debugging.

**Comment by munjalpatel** [comment]
+1 -- I also need this functionality.

**Comment by aprct** [comment]
+1

We can't develop without errors, unfortunately. Will be looking into something else until this is addressed.

**Comment by wwalser** [comment]
What you want has been addressed [here](https://github.com/acdlite/redux-promise/pull/13). 

Until a new version is published to NPM, the following work when you're using flux standard actions:
```javascript
const asyncAction = performAsyncAction();
dispatch(asyncAction);
asyncAction.catch(err => console.log("here is my error:", err));
```

```javascript
dispatch(performAsyncAction())
    .then(asyncActionResult => {
        if (asyncActionResult.error) {
            console.log("here is my error:", asyncActionResult.payload);
        }
    });
```

**Comment by pocesar** [comment]
that's actually how promises work. if you decide to use something like bluebird, it'll emit verbose warnings with stacktraces about unhandled rejections. you're in charge of handling your errors (as you would in try / catch statements, if / elses, etc)

**Comment by benjamingr** [comment]
@pocesar native promises and most libraries (NPO and RSVP lagging behind, but it's not a huge deal anymore) now emit warnings. This issue was about getting some indication about the error. 

Note that this issue is old, and has since been addressed in both popular middlewares that do promises, I just forgot to close it.
